/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import { useCharacterAnimations } from "../contexts/CharacterAnimations";
import { useCharacterCustomization } from "../contexts/characterCustomizationContext";

const WomenModel = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/woman.gltf");
  const { setAnimations, animationIndex } = useCharacterAnimations();
  const { actions, names } = useAnimations(animations, group);
  
  const {
    hairColor,
    setHairColor,
    eyes,
    setEyes,
    mouth,
    setMouth,
    glassesColor,
    setGlassesColor,
    skinColor,
    setSkinColor,
    shirtColor,
    setShirtColor,
    pantsColor,
    setPantsColor,
    shoesColor,
    setShoesColor,
    lacesColor,
    setLacesColor,
    soleColor,
    setSoleColor
  } = useCharacterCustomization();

  useEffect(() => {
    setAnimations(names);
  }, [names]);

  useEffect(() => {
    actions[names[animationIndex]].reset().fadeIn(0.5).play();
    return () => {
      actions[names[animationIndex]].fadeOut(0.5);
    };
  }, [animationIndex]);

  useEffect(() => {
    setMouth(`#${materials.Mouth.color.getHexString()}`);
    setGlassesColor(`#${materials.Glasses.color.getHexString()}`);
    setEyes(`#${materials.Eyes.color.getHexString()}`);
    setHairColor(`#${materials.Hair.color.getHexString()}`);
    setSkinColor(`#${materials.Skin.color.getHexString()}`);
    setShirtColor(`#${materials.Shirt.color.getHexString()}`);
    setPantsColor(`#${materials.Pants.color.getHexString()}`);
    setShoesColor(`#${materials.Shoes.color.getHexString()}`);
    setLacesColor(`#${materials.Laces.color.getHexString()}`);
    setSoleColor(`#${materials.Sole.color.getHexString()}`);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              castShadow
              name="Mesh019"
              geometry={nodes.Mesh019.geometry}
              material={materials.Glasses}
              skeleton={nodes.Mesh019.skeleton}
            >
              <meshStandardMaterial {...materials.Glasses} color={glassesColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_1"
              geometry={nodes.Mesh019_1.geometry}
              material={materials.Eyes}
              skeleton={nodes.Mesh019_1.skeleton}
            >
              <meshStandardMaterial {...materials.Eyes} color={eyes} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_2"
              geometry={nodes.Mesh019_2.geometry}
              material={materials.Hair}
              skeleton={nodes.Mesh019_2.skeleton}
            >
              <meshStandardMaterial {...materials.Hair} color={hairColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_3"
              geometry={nodes.Mesh019_3.geometry}
              material={materials.Skin}
              skeleton={nodes.Mesh019_3.skeleton}
            >
              <meshStandardMaterial {...materials.Skin} color={skinColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_4"
              geometry={nodes.Mesh019_4.geometry}
              material={materials.Mouth}
              skeleton={nodes.Mesh019_4.skeleton}
            >
              <meshStandardMaterial {...materials.Mouth} color={mouth} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_5"
              geometry={nodes.Mesh019_5.geometry}
              material={materials.Shirt}
              skeleton={nodes.Mesh019_5.skeleton}
            >
              <meshStandardMaterial {...materials.Shirt} color={shirtColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_6"
              geometry={nodes.Mesh019_6.geometry}
              material={materials.Pants}
              skeleton={nodes.Mesh019_6.skeleton}
            >
              <meshStandardMaterial {...materials.Pants} color={pantsColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_7"
              geometry={nodes.Mesh019_7.geometry}
              material={materials.Shoes}
              skeleton={nodes.Mesh019_7.skeleton}
            >
              <meshStandardMaterial {...materials.Shoes} color={shoesColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_8"
              geometry={nodes.Mesh019_8.geometry}
              material={materials.Sole}
              skeleton={nodes.Mesh019_8.skeleton}
            >
              <meshStandardMaterial {...materials.Sole} color={soleColor} />
            </skinnedMesh>
            <skinnedMesh
              castShadow
              name="Mesh019_9"
              geometry={nodes.Mesh019_9.geometry}
              material={materials.Laces}
              skeleton={nodes.Mesh019_9.skeleton}
            >
              <meshStandardMaterial {...materials.Laces} color={lacesColor} />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  );
};

export default WomenModel;

useGLTF.preload("/woman.gltf");
